Array manipulation 1
samlee0258/c1222-code-solutions pull request #47
Opened 2022-12-22 04:07 UTC by samlee0258

<img width="451" alt="Screenshot 2022-12-21 at 8 03 43 PM" src="https://user-images.githubusercontent.com/110208589/209053474-fc4c5fc9-2f7d-4d0d-8cce-e7f1c407bcfb.png">

2022-12-27 23:21 UTC, codingcodymiller requested changes

2022-12-27 23:21 UTC, codingcodymiller commented on array-manipulation-1/src/reverse.js
> +    if (i !== -1) {
This conditional shouldn't be necessary

2022-12-27 23:21 UTC, codingcodymiller commented on array-manipulation-1/src/tail.js
> +    if (i !== 0) {
If you start the loop at `1`, this conditional will not be needed

2022-12-29 00:34 UTC, samlee0258 commented on array-manipulation-1/src/reverse.js
> +    if (i !== -1) {
<img width="1011" alt="Screenshot 2022-12-28 at 4 33 27 PM" src="https://user-images.githubusercontent.com/110208589/209888940-25ff490e-b4d4-4210-b582-0dada9483788.png">

2022-12-29 00:34 UTC, samlee0258 commented on array-manipulation-1/src/tail.js
> +    if (i !== 0) {
<img width="1019" alt="Screenshot 2022-12-28 at 4 33 43 PM" src="https://user-images.githubusercontent.com/110208589/209888946-c4c7256c-316b-4693-b066-8346bedf3694.png">

2023-01-09 19:30 UTC, codingcodymiller approved these changes

2023-01-19 17:54 UTC, merged