String manipulation 2
samlee0258/c1222-code-solutions pull request #61
Opened 2023-01-10 08:15 UTC by samlee0258

<img width="432" alt="Screenshot 2023-01-10 at 12 13 56 AM" src="https://user-images.githubusercontent.com/110208589/211497103-16e7e7f4-4c11-4ebf-9911-c5c4e1800946.png">

2023-01-19 17:55 UTC, codingcodymiller requested changes

2023-01-19 17:55 UTC, codingcodymiller commented on string-manipulation-2/src/capitalize-word.js
> +    outputArr.push(word.charAt(0).toUpperCase() + word.slice(1, 4) + word.charAt(4).toUpperCase() + word.slice(5, 10));
You can just `return "JavaScript"`, this is a very special case, so you don't need to build the output programmatically

2023-01-19 18:03 UTC, samlee0258 commented on string-manipulation-2/src/capitalize-word.js
> +    outputArr.push(word.charAt(0).toUpperCase() + word.slice(1, 4) + word.charAt(4).toUpperCase() + word.slice(5, 10));
<img width="728" alt="Screenshot 2023-01-19 at 10 01 19 AM" src="https://user-images.githubusercontent.com/110208589/213524061-555f0b92-4a3f-42fa-ac43-d9969f66f06f.png">

2023-01-20 21:43 UTC, codingcodymiller approved these changes

2023-01-20 21:59 UTC, merged