Completed html-forms exercise.
samlee0258/c1222-code-solutions pull request #7
Opened 2022-12-06 20:01 UTC by samlee0258

![Kapture 2022-12-06 at 11 58 40](https://user-images.githubusercontent.com/110208589/206010626-eff758f0-b324-4193-84f5-12bb37b59615.gif)

2022-12-06 22:07 UTC, codingcodymiller requested changes

2022-12-06 22:07 UTC, codingcodymiller commented on html-forms/index.html
> +      <label>Email</label>
This `label` is not properly configured to pair with its form control element.

2022-12-06 22:07 UTC, codingcodymiller commented on html-forms/index.html
> +        <label>Comments</label>
This `label` is not properly configured to pair with its form control element.

2022-12-06 23:19 UTC, samlee0258 commented on html-forms/index.html
> +        <label>Comments</label>
<img width="556" alt="Screenshot 2022-12-06 at 3 03 11 PM" src="https://user-images.githubusercontent.com/110208589/206046156-35ce0dd9-cb57-4725-94fa-f465624e61c4.png">

2022-12-07 22:21 UTC, codingcodymiller requested changes
This is still not configured correctly. You should be able to click on the label to put focus on the form control element it is labeling.

2022-12-08 18:20 UTC, codingcodymiller approved these changes

2022-12-08 21:44 UTC, merged